// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp7pBfZ6Pdb-2_APzr0EAcZf3Au8urFGY',
    appId: '1:1015485509659:web:e5eb48f906e29476db08be',
    messagingSenderId: '1015485509659',
    projectId: 'nutritrackerapp-c908b',
    authDomain: 'nutritrackerapp-c908b.firebaseapp.com',
    databaseURL: 'https://nutritrackerapp-c908b-default-rtdb.firebaseio.com',
    storageBucket: 'nutritrackerapp-c908b.appspot.com',
    measurementId: 'G-C35Z87BKN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDciyszWLgsmU0TP7XXoAHgxUThRUumeEA',
    appId: '1:1015485509659:android:58247503b595de58db08be',
    messagingSenderId: '1015485509659',
    projectId: 'nutritrackerapp-c908b',
    databaseURL: 'https://nutritrackerapp-c908b-default-rtdb.firebaseio.com',
    storageBucket: 'nutritrackerapp-c908b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYWG_-15ovS07DxHH-gyi0MbYkrsjREGc',
    appId: '1:1015485509659:ios:0a6f0860897c3c04db08be',
    messagingSenderId: '1015485509659',
    projectId: 'nutritrackerapp-c908b',
    databaseURL: 'https://nutritrackerapp-c908b-default-rtdb.firebaseio.com',
    storageBucket: 'nutritrackerapp-c908b.appspot.com',
    androidClientId: '1015485509659-7753f8o6j0qebu847f06unuabqf3qaat.apps.googleusercontent.com',
    iosClientId: '1015485509659-n4snrvrp3vkr71jmcci2cuvonp830ikq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutritrackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYWG_-15ovS07DxHH-gyi0MbYkrsjREGc',
    appId: '1:1015485509659:ios:0a6f0860897c3c04db08be',
    messagingSenderId: '1015485509659',
    projectId: 'nutritrackerapp-c908b',
    databaseURL: 'https://nutritrackerapp-c908b-default-rtdb.firebaseio.com',
    storageBucket: 'nutritrackerapp-c908b.appspot.com',
    androidClientId: '1015485509659-7753f8o6j0qebu847f06unuabqf3qaat.apps.googleusercontent.com',
    iosClientId: '1015485509659-n4snrvrp3vkr71jmcci2cuvonp830ikq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutritrackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp7pBfZ6Pdb-2_APzr0EAcZf3Au8urFGY',
    appId: '1:1015485509659:web:a9203e3cbee4eba3db08be',
    messagingSenderId: '1015485509659',
    projectId: 'nutritrackerapp-c908b',
    authDomain: 'nutritrackerapp-c908b.firebaseapp.com',
    databaseURL: 'https://nutritrackerapp-c908b-default-rtdb.firebaseio.com',
    storageBucket: 'nutritrackerapp-c908b.appspot.com',
    measurementId: 'G-TH9SJCPJN4',
  );

}